#+title: Configurations

All kinds of textual configuration files that can potentially get shared among multiple machines.

* Emacs

** Prerequisites

- Using [[https://develop.spacemacs.org/][Spacemacs]]
- Dependencies
  - [[https://github.com/kanglmf/emacs-chinese-word-segmentation][~emacs-chinese-word-segmentation~]] :: How we navigate between Chinese words.
  - ~fcitx5~ :: If you are not using ~fcitx~, remove any thing in the file related to [[https://github.com/cute-jumper/fcitx.el][~fcitx.el~]].
  - [[https://dandavison.github.io/delta/installation.html][~git-delta~]] :: Magit add-on (~magit-delta~).
  - [[https://ledger-cli.org/docs.html][~ledger~]] :: If you ever use Ledger for accounting.
  - ~xclip~ :: For sharing clipboard with X system.
- Font Dependencies:
  - [[https://aur.archlinux.org/packages/ttf-all-the-icons][~ttf-all-the-icons~]] :: The icons needed by Spacemacs to display file type icons.
    (Otherwise you will need to run ~M-x all-the-icons-install-fonts~ yourself.)
  - [[https://github.com/be5invis/Sarasa-Gothic][~Sarasa Gothic~]] :: Mono-space fonts for CJK characters.
  - [[https://github.com/googlefonts/noto-emoji][~Noto Color Emoji~]] :: Emoji display.

** Recommendations

- Accommodate ~org-???-file_path~ to your liking (and find some ways to sync them with your phone).
- Adjusts font sizes to suit your monitor DPI.
- Use Emacs builds with native compilation enabled.
- Start Emacs as a daemon (with ~emacs.service~) and ~alias emacs="emacsclient -c"~​.
  If you are using fcitx, remember to ~systemctl --user edit emacs.service~ to add environment variables
  (like ~Environment=XMODIFIERS=@im=fcitx~).
- Personally, I also ~alias vim="emacsclient -nw -c"~.
- If you are using any proxy with environment variables like ~http_proxy~ set,
  whitelist ~mirrors.tuna.tsinghua.edu.cn~ (maybe with ~no_proxy~ (not tested yet)).
- Set up [[https://github.com/tecosaur/emacs-everywhere][~emacs-everywhere~]].
- Set up a shortcut to capture new org-mode to-do items (~emacsclient -c -e '(org-capture)'~).
- Put your projects under ~~/Workspaces~ (or else change the paths listed in ~mine/git-config~ in the ~.spacemacs~ config).

** Usage

#+begin_src shell
  ln -s absolute_path_to_this_file ~/.spacemacs
  git clone git_url_of_spacemacs
#+end_src

** Workarounds

*** Org mode broken?

See https://github.com/syl20bnr/spacemacs/issues/15896.

* Zsh

** Prerequisites

- ~oh-my-zsh~: In ~$HOME/.oh-my-zsh~.
- ~fasd~.
- ~zsh-syntax-highlighting~.

** Usage

#+begin_src shell
  ln -s absolute_path_to_this_file ~/.zshrc
#+end_src
