#+title: Scripts

Scripts, often bound to some shortcuts.

* ~scan-qr-on-screen.sh~

Lets the user select a region and then scans the QR code (if any) in it.

** Dependencies

- ~xfce4-screenshooter~
- ~qtqr~

* ~bing-wallpaper.sh~

Downloads today's Bing Wallpaper and sets it as the wallpaper.
It downloads to ~$HOME/.cache~ or ~$XDG_CACHE_HOME~ by default
and cleans the directory up when there are too many downloaded images.

Currently only XFCE is supported.

* ~map-wacom-input.py~

Maps Wacom pen movements with the stylus button down (mostly likely mapped to a mouse middle button)
to mouse scrolling events.
Probably only useful for devices without a dedicated scrolling button or panel.

** Dependencies

- ~python-pynput~
- ~python-libevdev~
- ~python-xlib~
- ~libwacom-list-local-devices~

* ~i3_window_back_and_forth.py~

Marks the most recently switched-to windows so that one can switch back to them
quickly with self-defined ~i3~ shortcuts.

** Dependencies

- [[https://i3wm.org/][~i3wm~]] (and ~i3-msg~)
- ~xorg-xprop~

** Usage

See [[file:../configs/i3_config][i3_config]] (search for ~con_mark~).
