#+title: Scripts

Scripts, often bound to some shortcuts.

* ~scan-qr-on-screen.sh~

Lets the user select a region and then scans the QR code (if any) in it.

** Dependencies

- ~xfce4-screenshooter~
- ~qtqr~

* ~bing-wallpaper.sh~

Downloads today's Bing Wallpaper and sets it as the wallpaper.
It downloads to ~$HOME/.cache~ or ~$XDG_CACHE_HOME~ by default
and cleans the directory up when there are too many downloaded images.

Currently only XFCE is supported.

* ~map-wacom-input.py~

Maps Wacom pen movements with the stylus button down (mostly likely mapped to a mouse middle button)
to mouse scrolling events.
Probably only useful for devices without a dedicated scrolling button or panel.

** Dependencies

- ~python-pynput~
- ~python-libevdev~
- ~python-xlib~
- ~libwacom-list-local-devices~

* i3 Scripts

** Dependencies

- [[https://i3wm.org/][~i3wm~]] (and ~i3-msg~)
- ~xorg-xprop~ (~i3_window_back_and_forth.py~)
- ~tk~ (~i3_maximize_window.py~)

** Usage

See [[file:../configs/i3_config][i3_config]] (search for ~con_mark~).

** Script List

*** ~i3_window_back_and_forth.py~

Marks the most recently switched-to windows so that one can switch back to them
quickly with self-defined ~i3~ shortcuts.

*** ~i3_splitv_tab_layout.py~

Rearranges windows in the current workspace in a horizontally split container with each side tabbed.

*** ~i3_maximize_window.py~

Simulates maximizing a window by moving it to a new workspace.

**** Behaviors

For example, if one binds =$mod+f= to ~i3_maximize_window.py~, they can then:

- Press =$mod+f= to maximize the focused window / any focused container.

  The script will create a placeholder window to "remember" to original position of the window / container.

- Navigate freely and do literally anything they like to the layout.

- Press =$mod+f= to restore the focused maximized window / container.

  It is done by swapping the placeholder with the container.
  (The placeholder is automatically closed after swapping or closing down the corresponding container.)

- Close the placeholder window to keep the maximized layout.

- Press =$mod+f= with the placeholder focused to switch to the corresponding maximized window.
